version: ''

services: 
    myredis: 
        image: 'redis:alpine'
    mypostgres: 
        image: 'postgres:alpine'
        environment: 
            - POSTGRES_PASSWORD=1qaz2wsx
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        volumes:
            - C:\Users\oem\.docker\devops\dockercompose\postgresdata:/var/lib/postgresql/data
    mybackend: 
        restart: always
        build:
            dockerfile: Dockerfile
            context: C:\Users\oem\.docker\devops\mybackend
        volumes:
                - /opt/app/node_modules
                - ./:/opt/app
        environment: 
                 - POSTGRES_PASSWORD=1qaz2wsx
                 - POSTGRES_DB=postgres
                 - POSTGRES_USER=postgres
                 - REDIS_HOST=myredis
                 - POSTGRES_HOST=mypostgres
        ports:
            - '5000:4000'
    myfrontend:
        restart: always
        build:
            dockerfile: dockerfile
            context: ./myfrontend
        volumes: 
            - /opt/app/node_modules
            - ./:/opt/app 
        ports: 
            - "3000:2000"